name: Build and Publish

on:
  push:
    tags:
      - 'alpha/v**'
      - 'beta/v**'
      - 'release/v**'
      - 'test/v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Get release type from github tag
        id: get_release_type
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[1];
      - name: Get file version from tag
        id: get_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[4];
      - name: Get main mc version from tag
        id: get_mc_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[3];
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          VERSION: ${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          VERSION: ${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: modonomicon-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}
          body: |
            [[Automated Build]]
            Changelog will be added on milestone close.
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/modonomicon-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          asset_name: modonomicon-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}.jar
          asset_content_type: application/java-archive
      - name: Upload to Curseforge
        id: curseforge
        uses: itsmeow/curseforge-upload@master
        if: ${{ steps.get_release_type.outputs.result }} != "test"
        with:
          token: ${{ secrets.CURSEFORGE_API_KEY }}
          project_id: 538392
          game_endpoint: minecraft
          file_path: ./build/libs/modonomicon-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          changelog: |-
            [Automated Build]
            ${{ steps.get_version.outputs.result }}
            Changelog for this build: https://github.com/klikli-dev/modonomicon/releases/tag/${{ steps.get_release_type.outputs.result }}%2Fv${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
            Find changes for all versions at https://github.com/klikli-dev/modonomicon/releases
          game_versions: Forge,Minecraft 1.19:1.19,Minecraft 1.19:1.19.1,Minecraft 1.19:${{ steps.get_mc_version.outputs.result }}
          display_name: modonomicon-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          release_type: ${{ steps.get_release_type.outputs.result }}
          relations: jei:optionalDependency