name: 'Close Milestone on Release'

on:
  release:
    types: [published]

jobs:
  update-milestone-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Update Milestone on Release'
        uses: klikli-dev/update-milestone-on-release@master
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}