on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:3.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
          USE_MILESTONE_TITLE: "true"
          FILENAME: release
      - name: Get Tag matching milestone
        id: milestonetag
        uses: klikli-dev/get-tag-from-milestone@main
      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.md
          token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          tag_name: ${{ steps.milestonetag.outputs.tag }}
